openapi: 3.0.0
info:
  title: 'ヘルスチェックAPI'
  version: '1.0.0'
  description: 'example API'
  contact:
    name: 'contact'
    url: 'https://github.com/lobmto/lobmto-nestjs-example.git'

servers:
  - url: 'http://localhost:3000'
    description: 'ローカル開発環境'

tags:
  - name: 'Health'
    description: 'ヘルスチェック'
  - name: 'Word'
    description: '単語'

paths:
  /health:
    get:
      tags:
        - 'Health'
      operationId: 'getHealth'
      summary: 'ヘルスチェックAPI'
      description: 'サービスの稼働状態を返却する'
      responses:
        '200':
          description: '正常'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ['UP']
                    example: 'UP'
                required:
                  - status
  /words:
    get:
      tags:
        - 'Word'
      operationId: 'getWordList'
      summary: '単語一覧取得API'
      description: '単語の一覧を取得する'
      responses:
        '200':
          description: '正常'
          content:
            application/json:
              schema:
                type: object
                properties:
                  words:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: '#/components/schemas/id'
                        word:
                          $ref: '#/components/schemas/word'
                        meaning:
                          $ref: '#/components/schemas/meaning'
                      required:
                        - id
                        - word
                        - meaning
                required:
                  - words

components:
  schemas:
    id:
      type: string
      format: uuid
    word:
      type: string
      example: 'example'
    meaning:
      type: string
      example: '例'
